### ISSUE TITLE
Event ratings and number of reviews appear on past events

### ISSUE THREAD

**Issue by Princesso** [TechMeetupsNG/eventplog#306]
child of #309

**Comment by innocentamadi** [comment]
Past events should have an extra line that reads:
```5 people rated [x]/10. View reviews```
![Screen Shot 2018-10-17 at 12.42.04 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5990548de98268001a78a735/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a379ed0c2f53415f4abc30254d58eeb9cb74fce36f34985619e8836d5a21c66b19feb9824eb705ba208a1d86e5bd8d18c5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e84a56a7173465e1703e6e0a.png)

**Comment by innocentamadi** [comment]
Expect the event to have two attributes: `no_of_reveiws`, `average_ratings`.

**Comment by innocentamadi** [comment]
Done: Events now have the two extra attributes
